Helm Chart: Ensure mariadb port value can be set (#4844)
* Helm Chart: Ensure mariadb port value can be set
- fixes #4843

* Allow for missing mariadb.port
Without this we get the opposite error
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
console:
- mariadb.port: Invalid type. Expected: integer, given: null
```
have now tested with and without mariadb.port and now in both cases we get the expected `DB_PORT` value in the rendered template