Fix istanbul cli error (replace with nyc) ``` require(...).create is not a function TypeError: require(...).create is not a function     at Object.<anonymous> (/home/travis/build/SUSE/stratos/node_modules/istanbul/lib/report/html.js:7:40) ```